services:
  database:
    container_name: "postgres-dev"
    image: "postgres:latest"
    env_file:
      - ../.env.development
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
